config/routes.rb
Receipt::Application.routes.draw do
  get "revenue/index"

  resources :purchases do
    member do
      post :sell
    end

    resources :expenses, :controller => "purchases/expenses"
  end

  resources :sales, :only => [:index, :show]
  resources :revenues do
    collection do
      get :list
    end
  end

  root :to => 'purchases#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :title, :description, :price
  belongs_to :purchase

  def self.calculate_all
    cash = 0
    all.each { |r| cash += r.price }
    return cash
  end

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  default_scope order('created_at desc')
  has_many :expenses
  attr_accessible :title, :description, :price

  def self.not_sold_yet
    Purchase.where(:sold => false)
  end

  def self.sold
    Purchase.where(:sold => true)
  end

  def self.calculate_sold
    cash = 0
    where(:sold => true).each { |r| cash += r.price }
    return cash
  end

  def self.calculate_bought
    cash = 0
    where(:sold => false).each { |r| cash += r.price }
    return cash
  end
end

app/models/revenue.rb
class Revenue < ActiveRecord::Base
  attr_accessible :title, :cash

  def self.calculate_all
    cash = 0
    all.each { |r| cash += r.cash }
    return cash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :prepare_for_mobile

  private

  def prepare_for_mobile
    request.format = :mobile
  end
end

app/controllers/purchases/expenses_controller.rb
class Purchases::ExpensesController < ApplicationController
  def new
    @purchase = Purchase.find(params[:purchase_id])
    @expense = @purchase.expenses.new
  end

  def create
    @purchase = Purchase.find(params[:purchase_id])
    expense = Expense.new(params[:expense])
    @purchase.expenses << expense
    redirect_to purchase_path(@purchase)
  end

  def destroy
    @purchase = Purchase.find(params[:purchase_id])
    expense = Expense.find(params[:id])
    expense.destroy
    redirect_to purchase_path(@purchase)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.not_sold_yet
  end

  def new
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new(params[:purchase])
    if @purchase.save
      redirect_to root_path
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def sell
    purchase = Purchase.find(params[:id])
    purchase.update_attribute(:sold, true)
    redirect_to purchases_path
  end
end

app/controllers/revenues_controller.rb
class RevenuesController < ApplicationController
  def index
    @revenue = Revenue.calculate_all
    @sold = Purchase.calculate_sold
    @bought = Purchase.calculate_bought
    @expense = Expense.calculate_all

    @total = (@revenue + @sold)
    @total -= @bought
    @total -= @expense
  end

  def list
    @revenues = Revenue.all
  end

  def new
    @revenue = Revenue.new
  end

  def create
    @revenue = Revenue.new(params[:revenue])
    if @revenue.save
      redirect_to list_revenues_path
    end
  end

  def destroy
    revenue = Revenue.find(params[:id])
    revenue.destroy
    redirect_to list_revenues_path
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def index
    @purchases = Purchase.sold
  end

  def show
    @purchase = Purchase.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def back(path=nil)
    if path.nil?
      path = purchases_path
    end
    link_to "Back", path, :"data-icon" => "back", :class => "ui-btn-left"
  end
end

app/helpers/purchases/expenses_helper.rb
module Purchases::ExpensesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/revenues_helper.rb
module RevenuesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receipt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Lion-Biler</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
  <script src="http://code.jquery.com/jquery-1.8.2.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div data-role="page">
    <%= yield %>
  </div>
</body>
</html>

app/views/purchases/_footer.mobile.erb
<div data-role="footer" data-id="footer" data-position="fixed">
  <div data-role="navbar">
    <ul>
      <li><%= link_to "Købt", purchases_path, :"data-icon" => "plus", :"data-iconpos" => "notext", :class => "ui-btn-active" %></li>
      <li><%= link_to "Solgt", sales_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
      <li><%= link_to "Omsætning", revenues_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
    </ul>
  </div>
</div>

app/views/purchases/_purchase.mobile.erb
<li><a href="<%=purchase_path(purchase)%>"><h3><%=purchase.title%></h3><p><%=purchase.description%></p></a><span class="ui-li-count"><%=purchase.price%> kr,-</span></li>

app/views/purchases/expenses/_expense.mobile.erb
<li><a href="#"><h6><%=expense.title%></h6><p><%=expense.description%></p></a><span class="ui-li-count"><%=expense.price%> kr,-</span><%=link_to "", purchase_expense_path(@purchase, expense), :method => :delete, :confirm => true%></li>

app/views/purchases/expenses/new.mobile.erb
<div data-role="header">
  <h1>Tilføj udgifter</h1>
  <%= link_to "Back", purchase_path(@purchase), :"data-icon" => "back", :class => "ui-btn-left" %>
</div>

<div data-role="content">
  <%= form_for [@purchase, @expense] do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :price %>
    <%= f.text_field :price, :required => true %>

    <%= submit_tag 'Tilføj udgifter' %>
  <% end %>
</div>

<%= render 'purchases/footer' %>

app/views/purchases/index.mobile.erb
<div data-role="header">
  <h1>Købt</h1>
  <%= link_to "Ny køb", new_purchase_path, :"data-icon" => "plus", :class => "ui-btn-right" %>
</div>

<div data-role="content">
  <% if @purchases.empty? %>
  <h4>Ingen varer til salg</h4>
  <% else %>
  <ul data-role="listview">
    <%= render @purchases %>
  </ul>
  <% end %>
</div>

<%= render 'footer' %>

app/views/purchases/new.mobile.erb
<div data-role="header">
  <h1>Købt</h1>
  <%= link_to "Back", purchases_path, :"data-icon" => "back", :class => "ui-btn-left" %>
</div>

<div data-role="content">
  <%= form_for @purchase do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :price %>
    <%= f.text_field :price, :required => true %>

    <%= submit_tag 'Add new' %>
  <% end %>
</div>

<%= render 'footer' %>

app/views/purchases/show.mobile.erb
<div data-role="header">
  <h1><%= @purchase.title %></h1>
  <%= back %>
  <%= link_to "Sælge", sell_purchase_path(@purchase), :confirm => true, :class => "ui-btn-right", :method => :post %>
</div>

<div data-role="content">
  <%=@purchase.description%><br />
  <%= @purchase.price %> Kr,-<br />

  <h4>Udgifter</h4>
  <ul data-role="listview" data-split-icon="delete">
    <%= render :partial => '/purchases/expenses/expense', :collection => @purchase.expenses %>
  </ul>

  <br />
  <%= button_to "Tilføj udgifter", new_purchase_expense_path(@purchase), :method => :get %>
</div>

<%= render 'footer' %>

app/views/revenues/_footer.mobile.erb
<div data-role="footer" data-id="footer" data-position="fixed">
  <div data-role="navbar">
    <ul>
      <li><%= link_to "Købt", purchases_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
      <li><%= link_to "Solgt", sales_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
      <li><%= link_to "Omsætning", revenues_path, :"data-icon" => "plus", :"data-iconpos" => "notext", :class => "ui-btn-active" %></li>
    </ul>
  </div>
</div>

app/views/revenues/_revenue.mobile.erb
<li>
  <a href="#"><%=revenue.title%></a><span class="ui-li-count"><%=revenue.cash%> kr,-</span>
  <%=link_to "", revenue_path(revenue), :method => :delete, :confirm => true%>
</li>

app/views/revenues/index.mobile.erb
<div data-role="header">
  <h1>Omsætning</h1>
</div>

<div data-role="content">
  <ul data-role="listview">
    <li><a href="<%=list_revenues_path%>"><h3>Omsætning</h3><p>blah..</p></a><span class="ui-li-count">+ <%=@revenue%> kr,-</span></li>
    <li><h3>Sold</h3><p>blah..</p><span class="ui-li-count">+ <%=@sold%> kr,-</span></li>
    <li><h3>Udgifter</h3><p>blah..</p><span class="ui-li-count">- <%=@expense%> kr,-</span></li>
    <li><h3>Bought</h3><p>blah..</p><span class="ui-li-count">- <%=@bought%> kr,-</span></li>


    <li data-role="list-divider">Total<span class="ui-li-count"><%=@total%> kr,-</span></li>
  </ul>
</div>

<%= render 'footer' %>

app/views/revenues/list.mobile.erb
<div data-role="header">
  <h1>Omsætning list</h1>
  <%= back(revenues_path) %>
  <%= link_to "Tilføj omsætning", new_revenue_path, :"data-icon" => "plus", :class => "ui-btn-right" %>
</div>

<div data-role="content">
  <% if @revenues.empty? %>
  <h4>Ingen omsætning</h4>
  <% else %>
  <ul data-role="listview" data-split-icon="delete">
    <%= render :partial => 'revenue', :collection => @revenues %>
  </ul>
  <% end %>
</div>

<%= render 'footer' %>

app/views/revenues/new.mobile.erb
<div data-role="header">
  <h1>Ny omsætning</h1>
  <%= link_to "Back", list_revenues_path, :"data-icon" => "back", :class => "ui-btn-left" %>
</div>

<div data-role="content">
  <%= form_for @revenue do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, :required => true %>

    <%= f.label :cash %>
    <%= f.text_field :cash, :required => true %>

    <%= submit_tag 'Add new' %>
  <% end %>
</div>

<%= render 'footer' %>

app/views/sales/_footer.mobile.erb
<div data-role="footer" data-id="footer" data-position="fixed">
  <div data-role="navbar">
    <ul>
      <li><%= link_to "Købt", purchases_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
      <li><%= link_to "Solgt", sales_path, :"data-icon" => "plus", :"data-iconpos" => "notext", :class => "ui-btn-active" %></li>
      <li><%= link_to "Omsætning", revenues_path, :"data-icon" => "plus", :"data-iconpos" => "notext" %></li>
    </ul>
  </div>
</div>

app/views/sales/_sale.mobile.erb
<li><a href="<%=sale_path(sale)%>"><h3><%=sale.title%></h3><p><%=sale.description%></p></a><span class="ui-li-count"><%=sale.price%> kr,-</span></li>

app/views/sales/index.mobile.erb
<div data-role="header">
  <h1>Solgt</h1>
</div>

<div data-role="content">
  <% if @purchases.empty? %>
  <h4>Ingen varer solgt</h4>
  <% else %>
  <ul data-role="listview">
    <%= render :partial => 'sale', :collection => @purchases %>
  </ul>
  <% end %>
</div>

<%= render 'footer' %>

app/views/sales/show.mobile.erb
<div data-role="header">
  <h1><%= @purchase.title %></h1>
  <%= back(sales_path) %>
</div>

<div data-role="content">
  <%=@purchase.description%><br />
  <%= @purchase.price %> Kr,-

  <% if @purchase.expenses.empty? %>
  <h4>Ingen udgifter</h4>
  <% else %>
  <h4>Udgifter</h4>
  <ul data-role="listview" data-split-icon="delete">
    <%= render :partial => '/purchases/expenses/expense', :collection => @purchase.expenses %>
  </ul>
  <% end %>
</div>

<%= render 'footer' %>